### PR TITLE
Added Google Chart Tables

### PR DESCRIPTION
**Pull request by jasper-lyons**
This pretty simply added google charts 'Table' functionality to chartkick.

I've included basic tests (super basic), but there isn't much to test ruby side.

### CODE REVIEW

**Comment by samarthsikotara** [comment]
Awesome! when would it be merged? #waiting

**Comment by ankane** [comment]
Hey @jasper-lyons, thanks for the PR 👍  and sorry for the long delay. I don't plan to support additional chart types at this time, but will let you know if that changes.

**Comment by jasper-lyons** [comment]
@ankane No problem! Managing OSS is hard. Well done for saying no :)

**Comment by ankane** [comment]
Thanks for understanding :)

**Pull request closed without merging**
