### PR TITLE
Feature/trendline

### PR DESCRIPTION
**Pull request by JohnathanWeisner**
- Created a helper for trendline
- Documentation updated to include trendline

### CODE REVIEW

**Comment by aaronjplatt** [comment]
hey @ankane, any plans to merge scatter in? would love this graph.

**Comment by jankeesvw** [comment]
I would love it too!

**Comment by gsdean** [comment]
Any update on this being merged?

**Comment by ankane** [comment]
Cleaning up old PRs. Trendline functionality would still be cool, but it looks like Chart.js doesn't currently support it. Thanks again for putting this together @JohnathanWeisner 👍

**Pull request closed without merging**
