### PR TITLE
Enable use of google annotations and style columns in chartkick.js

### PR DESCRIPTION
**Pull request by ckaiser79**
I have a line chart and need to annotate special dates in this line. To achieve this, I changed the date structure send to Chartkick:

``` javascript
var data = {
   "name": "validation line",
   "data":[ 
      ["2015-09-30",166,null,null], // no annotations
      ["2015-10-15",242,"Test Starts","point { ...}"] // with annotatiosn and style
   ], 
   "types":[ "annotation", "style" ] // new: optional define additionals column roles
}
```

example

### CODE REVIEW

**Comment by CUnknown** [comment]
Looks like just what I need!

**Comment by solson** [comment]
This would be very useful for me!

**Comment by stvmachine** [comment]
Plz can you merge this??

**Comment by ankane** [comment]
Hey @ckaiser79, thanks for the PR 👍  and sorry for the *very long* delay. Unfortunately, this isn't a feature I'd like to support in Chartkick. For more advance functionality (like additional columns), it's recommended to use the charting library directly.

**Pull request closed without merging**
