### PR TITLE
Annotated

### PR DESCRIPTION
**Pull request by btrepp**
Adds in the annotation chart.
Javascript changes are the same pull request to chartkick.js

Refactored the helper methods to be shorter, and added in annotation_chart to the helper methods.

### CODE REVIEW

**Comment by francescor** [comment]
yes, this would be helpful

**Comment by ghilead** [comment]
+1

**Comment by samstickland** [comment]
+1

**Comment by ankane** [comment]
Hey @btrepp, thanks for the PR 👍  and sorry for the *very long* delay. I don't plan to support additional chart types at this time, but will let you know if that changes.

**Pull request closed without merging**
