### PR TITLE
Drop jQuery and Zepto deps

### PR DESCRIPTION
**Pull request by savayg**

### CODE REVIEW

**Comment by savayg** [comment]
Quickly tested with https://github.com/bodrovis/Sitepoint-source/tree/master/Graphs_Chartkick_Practice demo app

**Comment by ankane** [comment]
Thanks for the PR @savayg!

jQuery has additional features (namely JSONP and IE7 support), so I think we'd still want to use jQuery or Zepto if detected.

It'd be good to pull out the AJAX code into a separate function that takes `url`, `success`, and `error` as its arguments, so it's easy to tell what's generic AJAX code vs Chartkick specific code.

**Comment by ankane** [comment]
Also, I think we may be able to simplify the AJAX code. http://blog.garstasio.com/you-dont-need-jquery/ajax/#sending-and-receiving-json

**Comment by savayg** [comment]
Oops just saw you have a chartkick.js repo on its own, will do the PR there!

**Pull request closed without merging**
