### PR TITLE
fix for rails regarding sprockets version

### PR DESCRIPTION
**Pull request by guymaliar**
Hey guys, 
I'm running Rails 4.2 and I tried upgrading to sprockets 5.
Everything is running smooth except for `chartkick` failling on the Proc.new error.
This fixes it!

LMK what you guys think

### CODE REVIEW

**Comment by ankane** [comment]
Thanks Guy, what's the reason for checking if `> 3.5.2` rather than `>= 5`?

**Comment by gmaliar** [comment]
I am checking Sprockets version, I am sorry it's version 4 and not 5.
But right now it's 4.0.0.beta1 which by the standards it means a pre-release, so `4.0.0 > 4.0.0.beta1`, that way it won't pass

**Comment by ankane** [comment]
How about we do `>= 4.0.0.beta1`?

**Comment by guymaliar** [comment]
Yeah that makes sense

**Comment by ankane** [comment]
Great, thanks Guy! :+1:

**Pull request merged**
